// AUTO-GENERATED by tools/build_api_types.py — do not edit by hand.
// Hand-tuned signatures in types.d.ts override these via interface merging.
// Regenerate after changing *API exports: `python tools/build_api_types.py`

interface LancerAutomationsAPI {
    addGlobalBonus(actor: any, bonusData: any, options?: any): Promise<any>;
    applyFlaggedEffectToTokens(...args: any[]): Promise<any>;
    beginWeaponAttackFlow(weapon: any, options: any, extraData?: any): Promise<any>;
    beginWeaponThrowFlow(weapon: any, options: any, extraData?: any): Promise<any>;
    canEngage(token1: any, token2: any): Promise<any>;
    canProvokeReaction(triggering: any, reactor: any): Promise<any>;
    checkOverwatchCondition(reactor: any, mover: any, startPos: any): Promise<any>;
    delayedTokenAppearance(): Promise<any>;
    executeBarrage(actorOrToken: any, bypassMount?: any, preTarget?: any): Promise<any>;
    executeBasicAttack(actor: any, options?: any, extraData?: any): Promise<any>;
    executeContestedCheck(input1: any, stat1: any, input2: any, stat2: any, options?: any): Promise<any>;
    executeDeleteAllFlaggedEffect(...args: any[]): Promise<any>;
    executeDowntime(): Promise<any>;
    executeFall(paramToken: any): Promise<any>;
    executeGenerateScan(targetsArg: any): Promise<any>;
    executeGenericBonusMenu(actor?: any): Promise<any>;
    executeInvade(actorOrToken: any, bypassChoice?: any): Promise<any>;
    executeItemActivation(item: any, options?: any, extraData?: any): Promise<any>;
    executePackMacro(macroName: any, scope?: any): Promise<any>;
    executeReactorExplosion(token: any): Promise<any>;
    executeReactorMeltdown(tokenOrActor: any, turns?: any): Promise<any>;
    executeRest(token: any): Promise<any>;
    executeScanOnActivation(reactorToken: any): Promise<any>;
    executeSimpleActivation(actor: any, options?: any, extraData?: any): Promise<any>;
    executeSkirmish(actorOrToken: any, bypassMount?: any, preTarget?: any, weaponFilter?: any, opts?: any): Promise<any>;
    executeStandingUp(token: any): Promise<any>;
    executeTechAttack(target: any, options?: any, extraData?: any): Promise<any>;
    executeTeleport(token: any, cost: any): Promise<any>;
    findFlaggedEffectOnToken(...args: any[]): Promise<any>;
    getActivationIcon(actionOrActivation: any): Promise<any>;
    getAllFlaggedEffects(...args: any[]): Promise<any>;
    getHexGroundElevation(col: any, row: any, terrainAPI?: any): Promise<any>;
    getItemTags_WithBonus(item: any, actor: any): Promise<any>;
    getMaxItemRanges_WithBonus(item: any, actor: any): Promise<any>;
    getTokenDistance(token1: any, token2: any, includeElevation?: any): Promise<any>;
    gridScale(): Promise<any>;
    hasTallerSolidAdjacent(token: any, terrainAPI?: any): Promise<any>;
    injectBonusToFlowState(state: any, bonus: any): Promise<any>;
    isDisableable(item: any): Promise<any>;
    isItemDisabled(item: any): Promise<any>;
    openAddReserveDialog(tokenOrActor: any): Promise<any>;
    packMacros(): Promise<any>;
    processDurationEffects(triggerLabel: any, triggeringTokenId: any): Promise<any>;
    pushEffect(targetID: any, effect: any, duration: any, note: any, originID: any): Promise<any>;
    pushFlaggedEffect(...args: any[]): Promise<any>;
    regenerateScans(opts?: any): Promise<any>;
    registerDefaultGeneralReactions(): Promise<any>;
    registerDefaultItemReactions(): Promise<any>;
    removeEffectsFromTokens(...args: any[]): Promise<any>;
    removeFlaggedEffectFromTokens(...args: any[]): Promise<any>;
    scaleAuraStroke(aura: any): Promise<any>;
    setEffect(targetID: any, effectOrData: any, duration: any, note: any, originID: any, extraOptions?: any): Promise<any>;
    setFlaggedEffect(...args: any[]): Promise<any>;
    setItemDisabled(item: any, disabled: any): Promise<any>;
    setReaction(actorOrToken: any, value: any): Promise<any>;
    triggerDangerousZoneFlow(token: any, damageType?: any, damageValue?: any): Promise<any>;
    triggerFlaggedEffectImmunity(...args: any[]): Promise<any>;
    updateAllEngagements(options?: any): Promise<any>;
}
