// AUTO-GENERATED by tools/build_api_types.py — do not edit by hand.
// Hand-tuned signatures in types.d.ts override these via interface merging.
// Regenerate after changing *API exports: `python tools/build_api_types.py`

interface LancerAutomationsAPI {
    applyActorBonusTemplatesToTokens(actor: any, tokens: any): Promise<any>;
    applyActorTemplatesToTokens(actor: any, tokens: any): Promise<any>;
    applyFlaggedEffectToTokens(...args: any[]): Promise<any>;
    applyItemBonusTemplatesToTokens(item: any, tokens: any): Promise<any>;
    applyItemTemplatesToTokens(item: any, tokens: any): Promise<any>;
    beginWeaponAttackFlow(weapon: any, options: any, extraData?: any): Promise<any>;
    cleanupActorBonusesFromTokens(actor: any): Promise<any>;
    cleanupItemBonusesFromActor(item: any, actor: any): Promise<any>;
    delayedTokenAppearance(): Promise<any>;
    executeBasicAttack(actor: any, options?: any, extraData?: any): Promise<any>;
    executeDeleteAllFlaggedEffect(...args: any[]): Promise<any>;
    executePackMacro(macroName: any, scope?: any): Promise<any>;
    executeSkirmish(actorOrToken: any, bypassMount?: any, preTarget?: any, weaponFilter?: any, opts?: any): Promise<any>;
    executeTechAttack(target: any, options?: any, extraData?: any): Promise<any>;
    findFlaggedEffectOnToken(...args: any[]): Promise<any>;
    getAllFlaggedEffects(...args: any[]): Promise<any>;
    getHexGroundElevation(col: any, row: any, terrainAPI?: any): Promise<any>;
    getLinkedBonuses(source: any): Promise<any>;
    getLinkedEffects(source: any): Promise<any>;
    gridScale(): Promise<any>;
    hasTallerSolidAdjacent(token: any, terrainAPI?: any): Promise<any>;
    linkBonusToActor(options?: any): Promise<any>;
    linkBonusToItem(options?: any): Promise<any>;
    linkEffectToActor(options?: any): Promise<any>;
    linkEffectToItem(options?: any): Promise<any>;
    packMacros(): Promise<any>;
    processDurationEffects(triggerLabel: any, triggeringTokenId: any): Promise<any>;
    pushEffect(targetID: any, effect: any, duration: any, note: any, originID: any): Promise<any>;
    pushFlaggedEffect(...args: any[]): Promise<any>;
    registerDefaultGeneralReactions(): Promise<any>;
    registerDefaultItemReactions(): Promise<any>;
    removeEffectsFromTokens(...args: any[]): Promise<any>;
    removeFlaggedEffectFromTokens(...args: any[]): Promise<any>;
    scaleAuraStroke(aura: any): Promise<any>;
    setEffect(targetID: any, effectOrData: any, duration: any, note: any, originID: any, extraOptions?: any): Promise<any>;
    setFlaggedEffect(...args: any[]): Promise<any>;
    templateToEffectDescriptor(template: any): Promise<any>;
    triggerDangerousZoneFlow(token: any, damageType?: any, damageValue?: any): Promise<any>;
    triggerFlaggedEffectImmunity(...args: any[]): Promise<any>;
    unlinkBonusFromActor(options?: any): Promise<any>;
    unlinkBonusFromItem(options?: any): Promise<any>;
    unlinkEffectFromActor(options?: any): Promise<any>;
    unlinkEffectFromItem(options?: any): Promise<any>;
}
